### ISSUE TITLE
Feature request: fallback language

### ISSUE THREAD

**Issue by andi34** [andreasremdt/simple-translator#1]
Ist es möglich ein Fallback einzurichten?
Z.B. wenn in deutsch nicht alles übersetz ist, dass er dann für diese i18n Elemente auf z.B Englisch zurückgreift?

Default habe ich Englisch eingestellt, ich lade also den translator einmal normal und anschließend mit der entsprechenden Sprache. Keine optimale Lösung aber so sind alle i18n Elemente am Ende mit Text versehen.

```
translator.load();
translator.load(config.language);
```

**Comment by andreasremdt** [comment]
Thank you for the suggestion, I have added support for fallback languages in version 1.1.0. You can see the changes in this version [here](https://github.com/andreasremdt/simple-translator/blob/master/CHANGELOG.md).
