### ISSUE TITLE
Auto detecting language does not work

### ISSUE THREAD

**Issue by sgp86** [andreasremdt/simple-translator#10]
Hi,

I have FF78.0.1 in 3 lang versions. DE, ES, EN. 

Unfortunately, default lang is always EN, on all browser, even if I have detectLanguage: true option when creating new Translator(...),

**Comment by gusbemacbe** [comment]
Hello @andreasremdt !

Medium did not notify you answered me. As you asked me to report here, then @q193 has already open this issue, but I'll expand the details.

Not only my local website, your website hosted on CodeSandbox also does not work on Firefox. You can watch the GIF:

![Autodetecting language bug on Firefox](https://user-images.githubusercontent.com/2257024/86534465-09ba9b00-beaf-11ea-8f3b-84d6dcc90bc7.gif)

Compare it on Chrome:

![Autodetecting language on Chrome](https://user-images.githubusercontent.com/2257024/86534476-1b03a780-beaf-11ea-95c5-07116431ee99.gif)

**Comment by gusbemacbe** [comment]
I found the error:

```
Could not load /i18n/de.json.json. Please make sure that the path is correct. SyntaxError: Unexpected token < in JSON at position 0
```

@andreasremdt, you duplicated the extension, therefore, Firefox and Chrome did not find the files.

**Comment by gusbemacbe** [comment]
@andreasremdt 

Ah, I solved the problem. It worked on Firefox and on Chrome. You have already updated the JavaScript file. Your CodeSandbox project is outdated. 

@q193, you used the oudated JavaScript file, you have to download the updated JavaScript file from his repo. 

I will attach you a zip.

[Tradutor Simples.zip](https://github.com/andreasremdt/simple-translator/files/4875203/Tradutor.Simples.zip)

**Comment by andreasremdt** [comment]
Sorry for my late response, and thank you for looking into this. Indeed, the CodeSandbox is outdated and needs to be updated. I will try to do so within the next days.

**Comment by andreasremdt** [comment]
The CodeSandbox has been updated with the latest version, where it should work now. Let me know if there's still an issue.

**Comment by gusbemacbe** [comment]
@andreasremdt 

On CodeSandbox, there's still a same issue on Firefox. It is all OK on Chrome.

**Comment by andreasremdt** [comment]
Hm, that's interesting. Let me look into it again, I thought it worked.

**Comment by andreasremdt** [comment]
Hey @gusbemacbe, I released v2 of this library and with it a new version of the CodeSandbox example. Could you please test again and let me know if it works now? 

https://codesandbox.io/s/simple-translator-vanilllajs-e33ye

I sometimes experienced the same behavior you mentioned, and what fixed it for me was to press to reload button inside the CodeSandbox browser.

**Comment by gusbemacbe** [comment]
Hi @andreasremdt 

Sorry for my absence,. I had a lot of chores for the project.

Unfortunately it does not work on Firefox yet. 

https://gifyu.com/image/czIU

But it works on Chrome. 

I think you should report this bug to Firefox developers.
