### ISSUE TITLE
noticed this function isn't used

### ISSUE THREAD

**Issue by gwprice115** [andreasremdt/simple-translator#13]
Hey just wanted to let you know I noticed [this function](https://github.com/andreasremdt/simple-translator/blob/develop/src/translator.js#L17) isn't used. I ignored the underscore and called it in my main.js to get language detection to work, and it works great, so I was thinking maybe you just forgot to put it in the constructor or something.

Feel free to close if it's a utility method

Thanks for the great library!

**Comment by andreasremdt** [comment]
Ha! Nice catch, this method should definitely be used, thanks for pointing me to that. That ought to be fixed :)
