### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by andi34** [andreasremdt/simple-translator#6]
```
translator.js:73 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at translator.js:89
    at Array.reduce (<anonymous>)
    at Translator._getValueFromJSON (translator.js:89)
    at Translator._getValueFromJSON (translator.js:96)
    at Translator._getValueFromJSON (translator.js:96)
    at Translator._getValueFromJSON (translator.js:96)
    at Translator._getValueFromJSON (translator.js:96)
    at Translator._getValueFromJSON (translator.js:96)
    at Translator._getValueFromJSON (translator.js:96)
    at Translator._getValueFromJSON (translator.js:96)
```
It's stops translating at "`toggle_fs_button`" because it does not exist in the language file and also does not exist in the fallback language.

Any idea how to solve that issue? Normally it should use the `element.dataset.i18n` if it can not find any translation.

![Screenshot_2020-04-06_14-36-35](https://user-images.githubusercontent.com/6080900/78559336-8092ba00-7814-11ea-8bdd-ba413a18344a.png)

**Comment by andi34** [comment]
Might be a personal problem becuase the page get generated:
https://github.com/andi34/photobooth/blob/fallback-language/admin/index.php based on https://github.com/andi34/photobooth/blob/fallback-language/lib/configsetup.inc.php

**Comment by riiccardo** [comment]
same here

**Comment by riiccardo** [comment]
@andi34 I Think I found the problem

problem is you define `data-i18n=""` with no key

and if you define key but not define that key for other translate json files this problem apears

**Comment by andi34** [comment]
Right, but in this case there should only be the key instead what's defined for that key
https://github.com/andreasremdt/simple-translator/blob/6694bba6876ebc827e0264ad4a42509514956292/src/translator.js#L111

Was implemented on this PR https://github.com/andreasremdt/simple-translator/pull/2

**Comment by andi34** [comment]
And key exists in the html 
```
  <span data-i18n="toggle_fs_button">toggle_fs_button</span>
```
 It's only not in the language.json file.

There's no issue if it at least exists in the defined `defaultLanguage`, so it must not exist in every language.

Example:
If it exists inside the `en.json` (which is defined as `defaultLanguage`) but does not exist inside used `de.json` it'll show the English text which is fine and how it should work.

But on a completely missing key expected behavior would be to show, in my example only, `toggle_fs_button` because nothing is defined for it and keep translating everything following.

At the moment it stops translation once it reaches the not existing key even if everything after that exists inside the language.json.

**Comment by andi34** [comment]
I guess i found the issue, only no idea how to solve it properly:
https://github.com/andreasremdt/simple-translator/blob/6694bba6876ebc827e0264ad4a42509514956292/src/translator.js#L91-L97

It starts looping here and never stops:
We first call `_getValueFromJSON(key, json)` and text is empty 
--> now `text = this._getValueFromJSON(key, fallbackTranslation);` which again calls `_getValueFromJSON`
--> text is still empty 
-->  now `text = this._getValueFromJSON(key, fallbackTranslation);` is called again 
 and again calls `_getValueFromJSON`
--> and so on.

Guess this somehow sounds right.

**Comment by andi34** [comment]
Fixed by https://github.com/andreasremdt/simple-translator/pull/7

**Comment by andreasremdt** [comment]
Interesting bug, thanks for fixing it @andi34!
